In [1]:
import numpy as np

In [4]:
#creation of numpy array
x=np.array([1,2,3,4,5])
print(x)
print(type(x)) #ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# shape and size
print(x.size)
print(x.shape)
print(x.ndim)

5
(5,)
1


In [10]:
x2d=np.array([[1,2,3],[4,5,6]])
print(x2d)
#shape and size
print(x2d.size)
print(x2d.shape)

[[1 2 3]
 [4 5 6]]
6
(2, 3)


In [13]:
x25=np.random.randint(1,100,(5,5))
print(x25)

[[78 70 71 24 60]
 [87 99 74 17 91]
 [71 37 34 64 18]
 [63 87 87 98 22]
 [61 25 90 34 54]]


In [18]:
xseq1=np.arange(1,101,4)
print('1D matrix')
print(xseq1)
print(xseq1.size)
print('1D matrix reshaped to 2D Matrix')
print(xseq1.reshape(5,5))

1D matrix
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
1D matrix reshaped to 2D Matrix
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [19]:
xseq2=np.linspace(1,100,50)
print(xseq2.size,'elements')
print('1D matrix')
print(xseq2)
print('1D matrix reshaped to 2D Matrix')
print(xseq2.reshape(10,5))
print('1D matrix reshaped to 3D Matrix')
print(xseq2.reshape(5,5,2))


50 elements
1D matrix
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
1D matrix reshaped to 2D Matrix
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327

In [20]:
xseq2d=xseq2.reshape(10,5)
print(xseq2d)

[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.46938776  49.48979592]
 [ 51.51020408  53.53061224  55.55102041  57.57142857  59.59183673]
 [ 61.6122449   63.63265306  65.65306122  67.67346939  69.69387755]
 [ 71.71428571  73.73469388  75.75510204  77.7755102   79.79591837]
 [ 81.81632653  83.83673469  85.85714286  87.87755102  89.89795918]
 [ 91.91836735  93.93877551  95.95918367  97.97959184 100.        ]]


In [21]:
np.ones((5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing
- boolean filter
- maths and stats
- methods

In [22]:
x25

array([[78, 70, 71, 24, 60],
       [87, 99, 74, 17, 91],
       [71, 37, 34, 64, 18],
       [63, 87, 87, 98, 22],
       [61, 25, 90, 34, 54]])

In [23]:
#first row
print(x25[0])

[78 70 71 24 60]


In [24]:
#Last row
print(x25[-1])

[61 25 90 34 54]


In [25]:
print(x25[0,1]) #same as x25[0][1]

70


In [26]:
#1st column
print(x25[:,-0])
#2nd column
print(x25[:,1])
#last column
print(x25[:,-1])

[78 87 71 63 61]
[70 99 37 87 25]
[60 91 18 22 54]


In [27]:
# column 0 and 1 index
print(x25[:,[0,1]])

[[78 70]
 [87 99]
 [71 37]
 [63 87]
 [61 25]]


In [29]:
# column 0,1,2 index
print(x25[:,[0,1,2]])
#same thing as above
print(x25[:,:3])


[[78 70 71]
 [87 99 74]
 [71 37 34]
 [63 87 87]
 [61 25 90]]
[[78 70 71]
 [87 99 74]
 [71 37 34]
 [63 87 87]
 [61 25 90]]


In [34]:
# filtering data without numpy boolean filter is a bad idea
for i in x25:
    for j in i:
        if j<20:
            print(j)

17
18


In [35]:
x25<=20 # boolean filter

array([[False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [36]:
x25[x25<=20]

array([17, 18])

In [37]:
(x25 > 20) & (x25<70)

array([[False, False, False,  True,  True],
       [False, False, False, False, False],
       [False,  True,  True,  True, False],
       [ True, False, False, False,  True],
       [ True,  True, False,  True,  True]])

In [38]:
x25[(x25 > 20) & (x25<70)]

array([24, 60, 37, 34, 64, 63, 22, 61, 25, 34, 54])

In [40]:
np.append(x25,[1,2,3,4,5])

array([78, 70, 71, 24, 60, 87, 99, 74, 17, 91, 71, 37, 34, 64, 18, 63, 87,
       87, 98, 22, 61, 25, 90, 34, 54,  1,  2,  3,  4,  5])

In [45]:
np.append(x25,np.array([[1,2,3,5,6]]),axis=0)

array([[78, 70, 71, 24, 60],
       [87, 99, 74, 17, 91],
       [71, 37, 34, 64, 18],
       [63, 87, 87, 98, 22],
       [61, 25, 90, 34, 54],
       [ 1,  2,  3,  5,  6]])

In [49]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [51]:
a=np.random.randint(1,100,(3,2))
b=np.random.randint(1,100,(2,3))
print(a)
print(b)

[[50 58]
 [32 48]
 [36  9]]
[[37 28 36]
 [97 76 77]]


In [53]:
print(a.shape)
print(b.shape)

(3, 2)
(2, 3)


In [54]:
a.T # same as a.transpose()

array([[50, 32, 36],
       [58, 48,  9]])

In [56]:
print(np.hstack((a,b.T)))

[[50 58 37 97]
 [32 48 28 76]
 [36  9 36 77]]


In [57]:
print(np.hstack((a.T,b)))

[[50 32 36 37 28 36]
 [58 48  9 97 76 77]]


In [58]:
print(np.vstack((a,b.T)))
print(np.vstack((a.T,b)))

[[50 58]
 [32 48]
 [36  9]
 [37 97]
 [28 76]
 [36 77]]
[[50 32 36]
 [58 48  9]
 [37 28 36]
 [97 76 77]]
